#!/usr/bin/sh
PROJECT="devapps"
pyver="3.7" # min version
git config user.email "g_kl_es_sing_er@gmx.de"
#google_analytics_key="$(pass show google/analytics_key_blog)"
versioning=calver
#lit_prog_eval_match="on_demand" # we use locks
# list of '::' seperated words to fail when occurring in committed files:
blacklisted_words="$(pass show sensitive/axgkl)"
#conda_env="~/miniconda3/envs/mddocuments_py39"
mkdocs_port=2119
# for browser screenshots:
nodejs="source $HOME/miniconda3/etc/profile.d/conda.sh && conda activate nodejs && node"
browser="chromium-browser"
# mkdocs serve:
mkdocs_path="$PROJECT"

lp_eval=on_page_change
# giving us make docs, make tests, ..:
source ./make -a
