site_name: "devapps"
site_description: "Documentation building tools"
site_url: "http://devapps.pages.axpypi.com/devapps"
repo_url: "https://gitlab.axpypi.com/devapps/devapps"
repo_name: "devapps/devapps"



copyright: |
  Copyright &copy; 2012 - 2021 <a href="https://www.axpypi.com/"  target="_blank" rel="noopener">axpypi Innovation </a>

#
nav:
  - Overview: index.md
  - Installation:
    - Python: install/python.md
    - DevApps Packages: install/prod_inst.md
    - Installing A Development Version: install/dev_inst.md
    - "Setting up CI/CI": install/cicd.md
  - Projects:
    - About: projects/index.md
    - Resources: projects/resources.md
    - Usage: projects/usage.md
  - Developing:
    - Flags: dev/flags.md
    # :autodocs:
    - "App": autodocs/src/devapp/devapp.app.md
    # :autodocs:
    - Plugins: dev/plugins.md 
    - Tips: dev/tips.md 
  - About:
    - Contributing: about/contributing.md
    - Changelog: about/changelog.md
    - Credits: about/credits.md
    - TODO: about/todo.md

theme:
  features:
      - navigation.instant
  name: material
  custom_dir: docs/lcd
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: preference
    primary: orange
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    #- toc.autohide


markdown_extensions:
   - admonition
   - attr_list
   - markdown_include.include
   - pymdownx.emoji
   - pymdownx.magiclink
   - pymdownx.superfences
   - pymdownx.tabbed
   - pymdownx.tasklist
   - pymdownx.details
   - markdown.extensions.tables
   - markdown.extensions.footnotes
   - markdown.extensions.md_in_html:
   - pymdownx.superfences:
       preserve_tabs: true
       custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format
   - toc:
       permalink: "¤"
   - pymdownx.snippets:
       base_path: theme/src/_snippets
   - plantuml_markdown:
       server: https://axc2.axpypi.com/plantuml
       base_dir: docs/lcd/assets/plantuml
       format: svg

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://axiros.com/
    - icon: fontawesome/brands/skype
      link: https://join.skype.com/krSNYZqvEmJm
extra_css:
  - assets/css/xterm.min.css
extra_javascript:
  - javascript/tables.js
  - assets/javascript/tablesort.min.js
    # 4.9.0 -> TODO: rename
  - assets/javascript/Rx.min.js
  - assets/javascript/xterm.4.9.0.min.js
  - assets/javascript/xterm-addon-fit.min.js
  - assets/javascript/xterm-addon-search.min.js
  - assets/javascript/lc.js
  - assets/pymdownx-extras/extra-uml-30be4556.js

plugins:
  - search