{'429e0985ffa960461234d10dd097ae2c': [{'cmd': {'cmd': 'ops p -h'},
                                       'res': '$ ops p '
                                              '-h                                                            \n'
                                              '\n'
                                              '\n'
                                              'Devapp Project '
                                              'Creation                                                                         \n'
                                              '\n'
                                              'By providing the --init_at '
                                              '<project dir> switch we will '
                                              '(re-)initialize a project '
                                              'directory there, '
                                              'incl:                                                                                        \n'
                                              '\n'
                                              '- Installing available '
                                              'resources, like databases and '
                                              'tools within a given directory '
                                              '(conda_prefix)                                                                                              \n'
                                              '- Creating resource start '
                                              'wrappers in '
                                              '<project_dir>/bin                                         \n'
                                              '- Creating '
                                              'a                                                                                    \n'
                                              '\n'
                                              'Privilege escalation is not '
                                              'required for any of these '
                                              'steps, your system remains '
                                              'unchanged, except <project_dir> '
                                              'and '
                                              '<conda_prefix>                                                             \n'
                                              '\n'
                                              'Main command line flags '
                                              '[matching '
                                              '\x1b[1m\x1b[32mops_devapp.project\x1b[0m\x1b[39m\x1b[49m] '
                                              '(-hf for all '
                                              'flags):                      \n'
                                              '\x1b[32mappc    '
                                              '\x1b[1m\x1b[33madd_post_process_cmd     '
                                              "\x1b[0m\x1b[31m\x1b[49m''\x1b[39m                                                             \n"
                                              '\x1b[38;5;245mAdd this to all '
                                              'commands which have systemd '
                                              'service units. Intended for '
                                              'output redirection. Not applied '
                                              'when stdout is a '
                                              'tty.\x1b[39m                                                                   \n'
                                              '\x1b[38;5;245mExample: '
                                              "-appc='2>&1 | rotatelogs -e -n1 "
                                              '"$logfile" 1M\' ($logfile '
                                              'defined in wrapper -> use '
                                              'single '
                                              'quotes).\x1b[39m                                                                                     \n'
                                              '\x1b[38;5;245mTip: Use '
                                              'rotatelogs only on powers of 10 '
                                              '- spotted problems with 200M. '
                                              'Use 100M or 1G in that case. '
                                              '\x1b[39m                                                                                            \n'
                                              '\x1b[32mcp      '
                                              '\x1b[1m\x1b[33mconda_prefix             '
                                              '\x1b[0m\x1b[31m\x1b[49mdefault\x1b[39m                                                        \n'
                                              '\n'
                                              '\x1b[38;5;245m    Resources '
                                              'install location, except '
                                              'filesystem based ones. Env vars '
                                              'resolved.\x1b[39m                \n'
                                              '\n'
                                              '\x1b[38;5;245m    '
                                              'Aliases:\x1b[39m                                                                                    \n'
                                              '\x1b[38;5;245m    - local|l: '
                                              '<project_dir>/conda\x1b[39m                                                              \n'
                                              '\x1b[38;5;245m    - default|d: '
                                              '$HOME/miniconda3 (default path '
                                              'of '
                                              'conda)\x1b[39m                                       \n'
                                              '\x1b[38;5;245m    - current|c: '
                                              'Any current conda_prefix set '
                                              'when '
                                              'running.\x1b[39m                                     \n'
                                              '\x1b[38;5;245m    '
                                              '\x1b[39m                                                                                            \n'
                                              '\x1b[38;5;245m    Note: '
                                              'Installing resources outside '
                                              'the project keeps the project '
                                              'relocatable and resources '
                                              'reusable for other '
                                              'products.\x1b[39m                                                                     \n'
                                              '\x1b[38;5;245m     '
                                              '\x1b[39m                                                                                           \n'
                                              '\x1b[32mdamsu   '
                                              '\x1b[1m\x1b[33mdelete_all_matching_service_unit_files '
                                              "\x1b[0m\x1b[31m\x1b[49m''\x1b[39m                                               \n"
                                              '\x1b[38;5;245mThis removes all '
                                              'matching unit files calling '
                                              'devapp service wrappers. Say '
                                              '"service" to match all '
                                              '\x1b[39m                                                                                               \n'
                                              '\x1b[32mdi      '
                                              '\x1b[1m\x1b[33mdev_install              '
                                              '\x1b[0m\x1b[31m\x1b[49mFalse\x1b[39m                                                          \n'
                                              '\x1b[38;5;245mSet the project '
                                              'up in developer mode - incl. '
                                              'make and poetry file machinery '
                                              '\x1b[39m                    \n'
                                              '\x1b[32memrf    '
                                              '\x1b[1m\x1b[33medit_matching_resource_file '
                                              "\x1b[0m\x1b[31m\x1b[49m''\x1b[39m                                                          \n"
                                              '\x1b[38;5;245mOpen resource '
                                              'files in $EDITOR, matching '
                                              'given string in their content '
                                              '\x1b[39m                         \n'
                                              '\x1b[32mf       '
                                              '\x1b[1m\x1b[33mforce                    '
                                              '\x1b[0m\x1b[31m\x1b[49mFalse\x1b[39m                                                          \n'
                                              '\x1b[38;5;245mAssume y on all '
                                              'questions. Required when '
                                              'started w/o a tty '
                                              '\x1b[39m                                     \n'
                                              '\x1b[32mfr      '
                                              '\x1b[1m\x1b[33mforce_reinstall          '
                                              '\x1b[0m\x1b[31m\x1b[49mFalse\x1b[39m                                                          \n'
                                              '\x1b[38;5;245mDo not only '
                                              'install resources detected '
                                              'uninstalled but reinstall all '
                                              '\x1b[39m                           \n'
                                              '\x1b[32mfd      '
                                              '\x1b[1m\x1b[33mfs_dir                   '
                                              '\x1b[0m\x1b[31m\x1b[49mdefault\x1b[39m                                                        \n'
                                              '\n'
                                              '\x1b[38;5;245m    Filesystem '
                                              'based resource location. Env '
                                              'vars '
                                              'resolved.\x1b[39m                                      \n'
                                              '\x1b[38;5;245m    '
                                              'Aliases:\x1b[39m                                                                                    \n'
                                              '\x1b[38;5;245m    - local|l: '
                                              '<project_dir>/fs\x1b[39m                                                                 \n'
                                              '\x1b[38;5;245m    - default|d: '
                                              '$HOME/miniconda3/fs (default '
                                              'path of '
                                              'conda)\x1b[39m                                    \n'
                                              '\x1b[38;5;245m    - conda|c: '
                                              'Within '
                                              'conda_prefix/fs\x1b[39m                                                           \n'
                                              '\x1b[38;5;245m     '
                                              '\x1b[39m                                                                                           \n'
                                              '\x1b[32mia      '
                                              '\x1b[1m\x1b[33minit_at                  '
                                              "\x1b[0m\x1b[31m\x1b[49m''\x1b[39m                                                             \n"
                                              '\x1b[38;5;245mSet up project in '
                                              'given directory. env vars / '
                                              'relative dirs supported. '
                                              '\x1b[39m                         \n'
                                              '\x1b[32micau    '
                                              '\x1b[1m\x1b[33minit_create_all_units    '
                                              '\x1b[0m\x1b[31m\x1b[49mFalse\x1b[39m                                                          \n'
                                              '\x1b[38;5;245mIf set we create '
                                              'unit files for ALL service type '
                                              'resources '
                                              '\x1b[39m                                     \n'
                                              '\x1b[32micuf    '
                                              '\x1b[1m\x1b[33minit_create_unit_files   '
                                              "\x1b[0m\x1b[31m\x1b[49m''\x1b[39m                                                             \n"
                                              '\x1b[38;5;245mList service unit '
                                              'files you want to have created '
                                              'for systemctl --user.  '
                                              '\x1b[39m                        \n'
                                              '\x1b[38;5;241mValid: Entries in '
                                              'rsc.provides, rsc.cmd or '
                                              'rsc.exe (i.e. the filename of '
                                              'the wrapper in bin dir). Not: '
                                              'rsc.name.\x1b[39m                                                                                \n'
                                              '\x1b[32mirm     '
                                              '\x1b[1m\x1b[33minit_resource_match      '
                                              "\x1b[0m\x1b[31m\x1b[49m''\x1b[39m                                                             \n"
                                              '\x1b[38;5;245mInstall only '
                                              'matching resources. Examples: '
                                              '-irm "redis, hub" or -irm '
                                              "'!mysql, !redis' (! negates). "
                                              '\x1b[39m                                                                                             \n'
                                              '\x1b[32mis      '
                                              '\x1b[1m\x1b[33minstall_state            '
                                              '\x1b[0m\x1b[31m\x1b[49mFalse\x1b[39m                                                          \n'
                                              '\x1b[38;5;245mshow install '
                                              'state infos '
                                              '\x1b[39m                                                                       \n'
                                              '\x1b[32mlrf     '
                                              '\x1b[1m\x1b[33mlist_resources_files     '
                                              '\x1b[0m\x1b[31m\x1b[49mFalse\x1b[39m                                                          \n'
                                              '\x1b[38;5;245mShow available '
                                              'definition files. '
                                              '\x1b[39m                                                               \n'
                                              '\x1b[32m        '
                                              '\x1b[1m\x1b[33mlog_resources_fully      '
                                              '\x1b[0m\x1b[31m\x1b[49mFalse\x1b[39m                                                          \n'
                                              '\x1b[38;5;245mAlways output all '
                                              'settings of resources when '
                                              'logging \x1b[39m'}],
 '57c491f2a2b84627b5adb295989d80e8': [{'cmd': {'cmd': 'mkdir $HOME/myproject '
                                                      '&& cd $HOME/myproject '
                                                      '&& ls -lta '},
                                       'res': '$ mkdir $HOME/myproject && cd '
                                              '$HOME/myproject && ls '
                                              '-lta              \n'
                                              'total '
                                              '0                                                                                         \n'
                                              'drwxr-xr-x. 1 gk gk    0 Mar 24 '
                                              '18:13 '
                                              '\x1b[1m\x1b[34m.\x1b[0m\x1b[39m\x1b[49m                                                         \n'
                                              'drwx------. 1 gk gk 2484 Mar 24 '
                                              '18:13 '
                                              '\x1b[1m\x1b[34m..\x1b[0m\x1b[39m\x1b[49m'}],
 '764322ce44d40af5e460edeed0cc6492': [{'cmd': {'cmd': 'poetry debug'},
                                       'res': '$ poetry '
                                              'debug                                                        \n'
                                              '\n'
                                              '\x1b[1mPoetry\x1b[0m\x1b[39m\x1b[49m                                                                                          \n'
                                              '\x1b[34mVersion\x1b[39m: '
                                              '\x1b[32m1.1.13\x1b[39m                                                                                 \n'
                                              '\x1b[34mPython\x1b[39m:  '
                                              '\x1b[32m3.7.12\x1b[39m                                                                                 \n'
                                              '\n'
                                              '\x1b[1mVirtualenv\x1b[0m\x1b[39m\x1b[49m                                                                                      \n'
                                              '\x1b[34mPython\x1b[39m:         '
                                              '\x1b[32m3.7.12\x1b[39m                                                                          \n'
                                              '\x1b[34mImplementation\x1b[39m: '
                                              '\x1b[32mCPython\x1b[39m                                                                         \n'
                                              '\x1b[34mPath\x1b[39m:           '
                                              '\x1b[32m/home/gk/miniconda3/envs/devapps_py3.7\x1b[39m                                          \n'
                                              '\x1b[34mValid\x1b[39m:          '
                                              '\x1b[32mTrue\x1b[39m                                                                            \n'
                                              '\n'
                                              '\x1b[1mSystem\x1b[0m\x1b[39m\x1b[49m                                                                                          \n'
                                              '\x1b[34mPlatform\x1b[39m: '
                                              '\x1b[32mlinux\x1b[39m                                                                                 \n'
                                              '\x1b[34mOS\x1b[39m:       '
                                              '\x1b[32mposix\x1b[39m                                                                                 \n'
                                              '\x1b[34mPython\x1b[39m:   '
                                              '\x1b[32m/home/gk/miniconda3/envs/devapps_py3.7\x1b[39m'}],
 '8b90d9698b1efefa01d881d347e3494f': [{'cmd': 'ops project --init_at . '
                                              '--port_offset 2000 --force',
                                       'res': '$ ops project --init_at . '
                                              '--port_offset 2000 '
                                              '--force                  \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'chdir                          '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32margs\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject\x1b[0m\x1b[39m\x1b[49m         \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'Directories                    '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mconda_prefix\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/miniconda3(default)\x1b[0m\x1b[39m\x1b[49m '
                                              '\x1b[1m\x1b[32mfs_dir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/miniconda3/fs(default)\x1b[0m\x1b[39m\x1b[49m                                                \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[1m\x1b[38;5;124mwarning  '
                                              '\x1b[0m\x1b[39m\x1b[49m] '
                                              'Installing resources           '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              "\x1b[1m\x1b[32mresources\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m[{'conda_chan': "
                                              "'conda-forge', 'conda_pkg': "
                                              "'git fzf jq ripgrep fd-find "
                                              "httpie htop tmux', 'disabled': "
                                              "False, 'doc': '', 'installed': "
                                              "True, 'module': 'devapp', "
                                              "'module_dir': "
                                              "'/home/gk/repos/devapps/src/devapp', "
                                              "'name': 'lc_tools', 'path': "
                                              "'/home/gk/miniconda3/envs/lc_tools/bin', "
                                              "'provides': ['git', 'fzf', "
                                              "'jq', 'rg', 'fd', 'http', "
                                              "'htop', 'tmux'], 'run': "
                                              "'lc_tools', 'verify_present': "
                                              "'verify_tools'}, {'conda_chan': "
                                              "'kalefranz', 'conda_pkg': "
                                              "'httpd', 'disabled': False, "
                                              "'doc': '', 'installed': True, "
                                              "'module': 'devapp', "
                                              "'module_dir': "
                                              "'/home/gk/repos/devapps/src/devapp', "
                                              "'name': 'lc_tools_kf', 'path': "
                                              "'/home/gk/miniconda3/envs/lc_tools_kf/bin', "
                                              "'provides': ['rotatelogs'], "
                                              "'verify_present': "
                                              "'verify_tools'}, {'cmd': "
                                              "'redis-server', 'disabled': "
                                              "False, 'doc': '', 'installed': "
                                              "True, 'module': 'devapp', "
                                              "'module_dir': "
                                              "'/home/gk/repos/devapps/src/devapp', "
                                              "'name': 'redis_server', 'path': "
                                              "'/home/gk/miniconda3/envs/redis_server/bin', "
                                              "'pkg': 'redis', 'port': 6379, "
                                              "'run': 'redis_server', "
                                              "'systemd': "
                                              "'redis-server'}]\x1b[0m\x1b[39m\x1b[49m                                                                 \n"
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'create_project_dirs            '
                                              '[\x1b[38;5;5mops\x1b[39m]                                 \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'creating                       '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mdir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject/bin\x1b[0m\x1b[39m\x1b[49m      \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'creating                       '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mdir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject/data\x1b[0m\x1b[39m\x1b[49m     \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'creating                       '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mdir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject/log\x1b[0m\x1b[39m\x1b[49m      \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'creating                       '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mdir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject/work\x1b[0m\x1b[39m\x1b[49m     \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'creating                       '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mdir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject/conf\x1b[0m\x1b[39m\x1b[49m     \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'creating                       '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mdir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject/tmp\x1b[0m\x1b[39m\x1b[49m      \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'creating                       '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mdir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject/build\x1b[0m\x1b[39m\x1b[49m    \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'chdir                          '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32margs\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject\x1b[0m\x1b[39m\x1b[49m         \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:19\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'git_init                       '
                                              '[\x1b[38;5;5mops\x1b[39m]                                 \n'
                                              '\x1b[38;5;240mInitialized empty '
                                              'Git repository in '
                                              '/home/gk/myproject/.git/\x1b[39m'},
                                      {'cmd': 'tree -L 2',
                                       'res': '$ tree -L '
                                              '2                                                           \n'
                                              '\x1b[1m\x1b[34m.\x1b[0m\x1b[39m\x1b[49m                                                                                               \n'
                                              '├── '
                                              '\x1b[1m\x1b[34mbin\x1b[0m\x1b[39m\x1b[49m                                                                                         \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mfd\x1b[0m\x1b[39m\x1b[49m                                                                                      \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mfzf\x1b[0m\x1b[39m\x1b[49m                                                                                     \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mgit\x1b[0m\x1b[39m\x1b[49m                                                                                     \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mhtop\x1b[0m\x1b[39m\x1b[49m                                                                                    \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mhttp\x1b[0m\x1b[39m\x1b[49m                                                                                    \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mjq\x1b[0m\x1b[39m\x1b[49m                                                                                      \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mredis-server\x1b[0m\x1b[39m\x1b[49m                                                                            \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mrg\x1b[0m\x1b[39m\x1b[49m                                                                                      \n'
                                              '│\xa0\xa0 ├── '
                                              '\x1b[1m\x1b[32mrotatelogs\x1b[0m\x1b[39m\x1b[49m                                                                              \n'
                                              '│\xa0\xa0 └── '
                                              '\x1b[1m\x1b[32mtmux\x1b[0m\x1b[39m\x1b[49m                                                                                    \n'
                                              '├── '
                                              '\x1b[1m\x1b[34mbuild\x1b[0m\x1b[39m\x1b[49m                                                                                       \n'
                                              '├── '
                                              '\x1b[1m\x1b[34mconf\x1b[0m\x1b[39m\x1b[49m                                                                                        \n'
                                              '├── '
                                              '\x1b[1m\x1b[34mdata\x1b[0m\x1b[39m\x1b[49m                                                                                        \n'
                                              '├── '
                                              '\x1b[1m\x1b[34mlog\x1b[0m\x1b[39m\x1b[49m                                                                                         \n'
                                              '├── '
                                              '\x1b[1m\x1b[34mtmp\x1b[0m\x1b[39m\x1b[49m                                                                                         \n'
                                              '│\xa0\xa0 └── '
                                              '\x1b[1m\x1b[34mtmux\x1b[0m\x1b[39m\x1b[49m                                                                                    \n'
                                              '└── '
                                              '\x1b[1m\x1b[34mwork\x1b[0m\x1b[39m\x1b[49m                                                                                        \n'
                                              '\n'
                                              '8 directories, 10 files'}],
 '9790c7560fc3981794ea0380095bac86': [{'cmd': 'ops project '
                                              '--list_resources_files',
                                       'res': '$ ops project '
                                              '--list_resources_files                                  \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:18\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'Directories                    '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mconda_prefix\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/miniconda3(default)\x1b[0m\x1b[39m\x1b[49m '
                                              '\x1b[1m\x1b[32mfs_dir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/miniconda3/fs(default)\x1b[0m\x1b[39m\x1b[49m                                                \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:18\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'Listing Defined Resources      '
                                              '[\x1b[38;5;5mops\x1b[39m]                                 \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:18\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'details                        '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mjson\x1b[0m\x1b[39m\x1b[49m=[                          \n'
                                              '\x1b[90m  '
                                              '\x1b[39m{                                                                                             \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"conda_chan"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"conda-forge"\x1b[39m,                                                                \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"conda_pkg"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"git fzf jq ripgrep '
                                              'fd-find httpie htop '
                                              'tmux"\x1b[39m,                                 \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"disabled"\x1b[39m:\x1b[90m '
                                              '\x1b[94mfalse\x1b[39m,                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"doc"\x1b[39m:\x1b[90m '
                                              '\x1b[33m""\x1b[39m,                                                                                  \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"installed"\x1b[39m:\x1b[90m '
                                              '\x1b[94mtrue\x1b[39m,                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"module"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"devapp"\x1b[39m,                                                                         \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"module_dir"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"/home/gk/repos/devapps/src/devapp"\x1b[39m,                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"name"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"lc_tools"\x1b[39m,                                                                         \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"path"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"/home/gk/miniconda3/envs/lc_tools/bin"\x1b[39m,                                            \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"provides"\x1b[39m:\x1b[90m '
                                              '\x1b[39m[                                                                               \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"git"\x1b[39m,                                                                                    \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"fzf"\x1b[39m,                                                                                    \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"jq"\x1b[39m,                                                                                     \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"rg"\x1b[39m,                                                                                     \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"fd"\x1b[39m,                                                                                     \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"http"\x1b[39m,                                                                                   \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"htop"\x1b[39m,                                                                                   \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"tmux"\x1b[39m                                                                                    \n'
                                              '\x1b[90m    '
                                              '\x1b[39m],                                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"run"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"lc_tools"\x1b[39m,                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"verify_present"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"verify_tools"\x1b[39m                                                            \n'
                                              '\x1b[90m  '
                                              '\x1b[39m},                                                                                            \n'
                                              '\x1b[90m  '
                                              '\x1b[39m{                                                                                             \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"conda_chan"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"kalefranz"\x1b[39m,                                                                  \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"conda_pkg"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"httpd"\x1b[39m,                                                                       \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"disabled"\x1b[39m:\x1b[90m '
                                              '\x1b[94mfalse\x1b[39m,                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"doc"\x1b[39m:\x1b[90m '
                                              '\x1b[33m""\x1b[39m,                                                                                  \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"installed"\x1b[39m:\x1b[90m '
                                              '\x1b[94mtrue\x1b[39m,                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"module"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"devapp"\x1b[39m,                                                                         \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"module_dir"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"/home/gk/repos/devapps/src/devapp"\x1b[39m,                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"name"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"lc_tools_kf"\x1b[39m,                                                                      \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"path"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"/home/gk/miniconda3/envs/lc_tools_kf/bin"\x1b[39m,                                         \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"provides"\x1b[39m:\x1b[90m '
                                              '\x1b[39m[                                                                               \n'
                                              '\x1b[90m      '
                                              '\x1b[33m"rotatelogs"\x1b[39m                                                                              \n'
                                              '\x1b[90m    '
                                              '\x1b[39m],                                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"verify_present"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"verify_tools"\x1b[39m                                                            \n'
                                              '\x1b[90m  '
                                              '\x1b[39m},                                                                                            \n'
                                              '\x1b[90m  '
                                              '\x1b[39m{                                                                                             \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"cmd"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"redis-server"\x1b[39m,                                                                      \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"disabled"\x1b[39m:\x1b[90m '
                                              '\x1b[94mfalse\x1b[39m,                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"doc"\x1b[39m:\x1b[90m '
                                              '\x1b[33m""\x1b[39m,                                                                                  \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"installed"\x1b[39m:\x1b[90m '
                                              '\x1b[94mtrue\x1b[39m,                                                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"module"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"devapp"\x1b[39m,                                                                         \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"module_dir"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"/home/gk/repos/devapps/src/devapp"\x1b[39m,                                          \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"name"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"redis_server"\x1b[39m,                                                                     \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"path"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"/home/gk/miniconda3/envs/redis_server/bin"\x1b[39m,                                        \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"pkg"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"redis"\x1b[39m,                                                                             \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"port"\x1b[39m:\x1b[90m '
                                              '\x1b[94m6379\x1b[39m,                                                                               \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"run"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"redis_server"\x1b[39m,                                                                      \n'
                                              '\x1b[90m    '
                                              '\x1b[94m"systemd"\x1b[39m:\x1b[90m '
                                              '\x1b[33m"redis-server"\x1b[39m                                                                   \n'
                                              '\x1b[90m  '
                                              '\x1b[39m}                                                                                             \n'
                                              ']                                                                                               \n'
                                              '\n'
                                              '[                                                                                               \n'
                                              '\x1b[90m    \x1b[33m"  i   '
                                              "lc_tools ['git', 'fzf', 'jq', "
                                              "'rg', 'fd', 'http', 'htop', "
                                              '\'tmux\']"\x1b[39m,                  \n'
                                              '\x1b[90m    \x1b[33m"  i   '
                                              'lc_tools_kf '
                                              '[\'rotatelogs\']"\x1b[39m,                                                         \n'
                                              '\x1b[90m    \x1b[33m"s i   '
                                              'redis-server '
                                              '"\x1b[39m                                                                       \n'
                                              ']'}],
 'bbb0295e0931845c001a33c958ecc728': [{'cmd': {'cmd': 'ops project --init_at=. '
                                                      '--init_create_unit_files=redis-server '
                                                      '--force'},
                                       'res': '$ ops project --init_at=. '
                                              '--init_create_unit_files=redis-server '
                                              '--force                                                                                               \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'chdir                          '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32margs\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject\x1b[0m\x1b[39m\x1b[49m         \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'Directories                    '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mconda_prefix\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/miniconda3(default)\x1b[0m\x1b[39m\x1b[49m '
                                              '\x1b[1m\x1b[32mfs_dir\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/miniconda3/fs(default)\x1b[0m\x1b[39m\x1b[49m                                                \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'verify_systemctl_availability  '
                                              '[\x1b[38;5;5mops\x1b[39m]                                 \n'
                                              'systemctl is '
                                              '/usr/bin/systemctl                                                                 \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[1m\x1b[38;5;124mwarning  '
                                              '\x1b[0m\x1b[39m\x1b[49m] '
                                              'Installing resources           '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              "\x1b[1m\x1b[32mresources\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m[{'conda_chan': "
                                              "'conda-forge', 'conda_pkg': "
                                              "'git fzf jq ripgrep fd-find "
                                              "httpie htop tmux', 'disabled': "
                                              "False, 'doc': '', 'installed': "
                                              "True, 'module': 'devapp', "
                                              "'module_dir': "
                                              "'/home/gk/repos/devapps/src/devapp', "
                                              "'name': 'lc_tools', 'path': "
                                              "'/home/gk/miniconda3/envs/lc_tools/bin', "
                                              "'provides': ['git', 'fzf', "
                                              "'jq', 'rg', 'fd', 'http', "
                                              "'htop', 'tmux'], 'run': "
                                              "'lc_tools', 'verify_present': "
                                              "'verify_tools'}, {'conda_chan': "
                                              "'kalefranz', 'conda_pkg': "
                                              "'httpd', 'disabled': False, "
                                              "'doc': '', 'installed': True, "
                                              "'module': 'devapp', "
                                              "'module_dir': "
                                              "'/home/gk/repos/devapps/src/devapp', "
                                              "'name': 'lc_tools_kf', 'path': "
                                              "'/home/gk/miniconda3/envs/lc_tools_kf/bin', "
                                              "'provides': ['rotatelogs'], "
                                              "'verify_present': "
                                              "'verify_tools'}, {'cmd': "
                                              "'redis-server', 'disabled': "
                                              "False, 'doc': '', 'installed': "
                                              "True, 'module': 'devapp', "
                                              "'module_dir': "
                                              "'/home/gk/repos/devapps/src/devapp', "
                                              "'name': 'redis_server', 'path': "
                                              "'/home/gk/miniconda3/envs/redis_server/bin', "
                                              "'pkg': 'redis', 'port': 6379, "
                                              "'run': 'redis_server', "
                                              "'systemd': "
                                              "'redis-server'}]\x1b[0m\x1b[39m\x1b[49m                                                                 \n"
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'create_project_dirs            '
                                              '[\x1b[38;5;5mops\x1b[39m]                                 \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'chdir                          '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32margs\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/myproject\x1b[0m\x1b[39m\x1b[49m         \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'have written unit file         '
                                              '[\x1b[38;5;5mops\x1b[39m] '
                                              '\x1b[1m\x1b[32mfn\x1b[0m\x1b[39m\x1b[49m=\x1b[1m\x1b[38;5;11m/home/gk/.config/systemd/user/redis-server-myproject.service\x1b[0m\x1b[39m\x1b[49m                                                                 \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'git_init                       '
                                              '[\x1b[38;5;5mops\x1b[39m]                                 \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'All project file created.      '
                                              '[\x1b[38;5;5mops\x1b[39m]                                 \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'Enabling systemd user service '
                                              'units. '
                                              '[\x1b[38;5;5mops\x1b[39m]                           \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'systemd --user available, '
                                              'calling daemon-reload '
                                              '[\x1b[38;5;5mops\x1b[39m]                \n'
                                              '\x1b[2m\x1b[38;5;5m03-24 '
                                              '17:13:23\x1b[0m\x1b[39m\x1b[49m '
                                              '[\x1b[38;5;2minfo     \x1b[39m] '
                                              'Done init.                     '
                                              '[\x1b[38;5;5mops\x1b[39m]'}],
 'dfb9ed5f3d9468406462d07976eab52c': [{'cmd': {'cmd': 'bin/redis-server',
                                               'timeout': 0.5},
                                       'res': '$ '
                                              'bin/redis-server                                                                              \n'
                                              '658614:C 24 Mar 2022 '
                                              '18:13:22.206 # oO0OoO0OoO0Oo '
                                              'Redis is starting '
                                              'oO0OoO0OoO0Oo               \n'
                                              '658614:C 24 Mar 2022 '
                                              '18:13:22.206 # Redis '
                                              'version=5.0.3, bits=64, '
                                              'commit=00000000, modified=0, '
                                              'pid=658614, just '
                                              'started                                                                         \n'
                                              '658614:C 24 Mar 2022 '
                                              '18:13:22.206 # Configuration '
                                              'loaded                                        \n'
                                              '658614:M 24 Mar 2022 '
                                              '18:13:22.207 * Increased '
                                              'maximum number of open files to '
                                              '10032 (it was originally set to '
                                              '1024).                                                                            \n'
                                              '                '
                                              '_._                                                                             \n'
                                              '           _.-``__ '
                                              "''-._                                                                        \n"
                                              '      _.-``    `.  `_.  '
                                              "''-._           Redis 5.0.3 "
                                              '(00000000/0) 64 '
                                              'bit                         \n'
                                              '  .-`` .-```.  ```\\/    _.,_ '
                                              "''-._                                                              \n"
                                              " (    '      ,       .-`  | "
                                              '`,    )     Running in '
                                              'standalone '
                                              'mode                              \n'
                                              " |`-._`-...-` __...-.``-._|'` "
                                              "_.-'|     Port: "
                                              '8379                                              \n'
                                              ' |    `-._   `._    /     '
                                              "_.-'    |     PID: "
                                              '658614                                             \n'
                                              "  `-._    `-._  `-./  _.-'    "
                                              "_.-'                                                              \n"
                                              " |`-._`-._    `-.__.-'    "
                                              "_.-'_.-'|                                                             \n"
                                              ' |    `-._`-._        '
                                              "_.-'_.-'    |           "
                                              'http://redis.io                                   \n'
                                              "  `-._    `-._`-.__.-'_.-'    "
                                              "_.-'                                                              \n"
                                              " |`-._`-._    `-.__.-'    "
                                              "_.-'_.-'|                                                             \n"
                                              ' |    `-._`-._        '
                                              "_.-'_.-'    "
                                              '|                                                             \n'
                                              "  `-._    `-._`-.__.-'_.-'    "
                                              "_.-'                                                              \n"
                                              "      `-._    `-.__.-'    "
                                              "_.-'                                                                  \n"
                                              '          `-._        '
                                              "_.-'                                                                      \n"
                                              '              '
                                              "`-.__.-'                                                                          \n"
                                              '\n'
                                              '658614:M 24 Mar 2022 '
                                              '18:13:22.208 # Server '
                                              'initialized                                          \n'
                                              '658614:M 24 Mar 2022 '
                                              '18:13:22.208 # WARNING '
                                              'overcommit_memory is set to 0! '
                                              'Background save may fail under '
                                              'low memory condition. To fix '
                                              'this issue add '
                                              "'vm.overcommit_memory = 1' to "
                                              '/etc/sysctl.conf and then '
                                              'reboot or run the command '
                                              "'sysctl vm.overcommit_memory=1' "
                                              'for this to take '
                                              'effect.                                                                                                \n'
                                              '658614:M 24 Mar 2022 '
                                              '18:13:22.208 # WARNING you have '
                                              'Transparent Huge Pages (THP) '
                                              'support enabled in your kernel. '
                                              'This will create latency and '
                                              'memory usage issues with Redis. '
                                              'To fix this issue run the '
                                              "command 'echo never > "
                                              "/sys/kernel/mm/transparent_hugepage/enabled' "
                                              'as root, and add it to your '
                                              '/etc/rc.local in order to '
                                              'retain the setting after a '
                                              'reboot. Redis must be restarted '
                                              'after THP is '
                                              'disabled.                                                                             \n'
                                              '658614:M 24 Mar 2022 '
                                              '18:13:22.208 * Ready to accept '
                                              'connections'}],
 'e617126e33050c4f4834b21684c66562': [{'cmd': {'cmd': 'systemctl --user '
                                                      '--no-pager start  '
                                                      'redis-server-myproject'},
                                       'res': '$ systemctl --user --no-pager '
                                              'start  redis-server-myproject'},
                                      {'cmd': {'assert': '(running)',
                                               'cmd': 'systemctl --user '
                                                      '--no-pager status '
                                                      'redis-server-myproject'},
                                       'res': '$ systemctl --user --no-pager '
                                              'status '
                                              'redis-server-myproject           \n'
                                              '\x1b[1m\x1b[32m●\x1b[0m\x1b[39m\x1b[49m '
                                              'redis-server-myproject.service '
                                              '- redis-server myproject  '
                                              'redis-server                         \n'
                                              '     Loaded: loaded '
                                              '(/home/gk/.config/systemd/user/redis-server-myproject.service; '
                                              'disabled; vendor preset: '
                                              'disabled)                                                                           \n'
                                              '     Active: '
                                              '\x1b[1m\x1b[32mactive '
                                              '(running)\x1b[0m\x1b[39m\x1b[49m '
                                              'since Thu 2022-03-24 18:13:23 '
                                              'CET; 240ms '
                                              'ago                      \n'
                                              '   Main PID: 658664 '
                                              '(bash)                                                                      \n'
                                              '      Tasks: 5 (limit: '
                                              '18356)                                                                   \n'
                                              '     Memory: '
                                              '1.8M                                                                               \n'
                                              '        CPU: '
                                              '9ms                                                                                \n'
                                              '     CGroup: '
                                              '/user.slice/user-1000.slice/user@1000.service/app.slice/redis-server-myproject.service                                                                                             \n'
                                              '             ├─658664 bash '
                                              '/home/gk/myproject/bin/redis-server                                  \n'
                                              '             └─658665 '
                                              '/home/gk/miniconda3/envs/redis_server/bin/redis-server '
                                              '*:6379             \n'
                                              '\n'
                                              'Mar 24 18:13:23 axgk '
                                              'systemd[1432]: Started '
                                              'redis-server myproject  '
                                              'redis-server.               \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:C '
                                              '24 Mar 2022 18:13:23.744 # '
                                              'oO0OoO0OoO0Oo Redis is starting '
                                              'oO0OoO0OoO0Oo                                                                    \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:C '
                                              '24 Mar 2022 18:13:23.744 # '
                                              'Redis version=5.0.3, bits=64, '
                                              'commit=00000000, modified=0, '
                                              'pid=658665, just '
                                              'started                              \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:C '
                                              '24 Mar 2022 18:13:23.744 # '
                                              'Configuration '
                                              'loaded                                                                                             \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:M '
                                              '24 Mar 2022 18:13:23.745 * '
                                              'Increased maximum number of '
                                              'open files to 10032 (it was '
                                              'originally set to '
                                              '1024).                                 \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:M '
                                              '24 Mar 2022 18:13:23.746 * '
                                              'Running mode=standalone, '
                                              'port=6379.                                                                              \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:M '
                                              '24 Mar 2022 18:13:23.746 # '
                                              'Server '
                                              'initialized                                                                                               \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:M '
                                              '24 Mar 2022 18:13:23.746 # '
                                              'WARNING overcommit_memory is '
                                              'set to 0! Background save may '
                                              'fail under low memory '
                                              'condition. To fix this issue '
                                              "add 'vm.overcommit_memory = 1' "
                                              'to /etc/sysctl.conf and then '
                                              'reboot or run the command '
                                              "'sysctl vm.overcommit_memory=1' "
                                              'for this to take '
                                              'effect.                                                     \n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:M '
                                              '24 Mar 2022 18:13:23.746 # '
                                              'WARNING you have Transparent '
                                              'Huge Pages (THP) support '
                                              'enabled in your kernel. This '
                                              'will create latency and memory '
                                              'usage issues with Redis. To fix '
                                              'this issue run the command '
                                              "'echo never > "
                                              "/sys/kernel/mm/transparent_hugepage/enabled' "
                                              'as root, and add it to your '
                                              '/etc/rc.local in order to '
                                              'retain the setting…\n'
                                              'Mar 24 18:13:23 axgk '
                                              'redis-server[658665]: 658665:M '
                                              '24 Mar 2022 18:13:23.746 * '
                                              'Ready to accept '
                                              'connections                                                                                      \n'
                                              'Hint: Some lines were '
                                              'ellipsized, use -l to show in '
                                              'full.'},
                                      {'cmd': {'cmd': 'systemctl --user '
                                                      '--no-pager stop   '
                                                      'redis-server-myproject'},
                                       'res': '$ systemctl --user --no-pager '
                                              'stop   redis-server-myproject'}]}